# Generated by Django 2.1.7 on 2021-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210317_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home and appliances', 'Home and appliances'), ('Electronics', 'Electronics'), ('AudioBooks', 'AudioBooks'), ('Smartphones & gadgets', 'Smartphones & gadgets')], max_length=255),
        ),
    ]
